### PR TITLE
Several improvements, replace PR #41

### PR DESCRIPTION
**Pull request by Napsty**
This replaces #41 .
The same additional options and checks (cpu) from @chicco27 are in this PR, including some fixes and cleanup

### CODE REVIEW

**Comment by MarcusCaepio** [comment]
lgtm

**Comment by HOSTED-POWER** [comment]
Indeed , it has faults, after using MarcusCaepio fix, it doesn't find getnodes.

Also:

`ES SYSTEM OK - Memory usage is at 64% (0 G from 1 G)|es_memory=692745744B;858993459;1020054732;0;1073741824`

Not a very pretty print: "0 G from 1 G"

And with disk it seems to have the same issue:

`ES SYSTEM OK - Disk usage is at 0% (0 G from 78 G)|es_disk=131313528B;67611675852;80288865075;0;84514594816`

**Comment by HOSTED-POWER** [comment]
PS: heap_used_percent and disk_used_percent are also outputted by Elasticsearch btw :)

**Comment by Napsty** [comment]
@MarcusCaepio Will check, thanks for verification!

@HOSTED-POWER 

> Not a very pretty print: "0 G from 1 G"

Use `-o M` in this case. Makes more sense in this scenario.

**Comment by Napsty** [comment]
@MarcusCaepio  @HOSTED-POWER  Please try the newest version:
https://raw.githubusercontent.com/Napsty/check_es_system/pull-41/check_es_system.sh

**Comment by Napsty** [comment]
@MarcusCaepio @HOSTED-POWER Will release on Friday, unless you find something else

**Comment by HOSTED-POWER** [comment]
It looks to work, however the disk check is strange:

 ./check_es_system.sh -H localhost -t disk -o M
ES SYSTEM OK - Disk usage is at 0% (226 M from 161263 M)|es_disk=237360520B;135277854720;160642452480;0;169097318400

df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1       158G   72G   80G  48% /

I would expect it to help me when the disk gets full, but it doesn't take into account the space used by other services. So probably the real disk free has to be reported instead of what elasticsearch is using on disk. Or at least find a way to take all space into account.

**Comment by Napsty** [comment]
Thanks for checking and the fast response!

> I would expect it to help me when the disk gets full, but it doesn't take into account the space used by other services. 

Yes, that's normal. The Elasticsearch API is only showing what Elasticsearch itself is using. Depending on the environment (e.g. chrooted) Elasticsearch cannot know about other services and the full disk usage. 

The plugin is no replacement for `check_disk`, it's only for pure Elasticsearch monitoring ;-)

**Comment by HOSTED-POWER** [comment]
I found another problem:

# '/usr/lib/nagios/plugins/check_es_system.sh' '-H' 'localhost' -L '-c' '500' '-t' 'jthreads' '-w' '500'
ES SYSTEM OK - Number of JVM threads is null|es_jvm_threads=null;500;500;;

# '/usr/lib/nagios/plugins/check_es_system.sh' '-H' 'localhost'  '-c' '500' '-t' 'jthreads' '-w' '500'
ES SYSTEM OK - Number of JVM threads is 185|es_jvm_threads=185;500;500;;

When using -L the jthreads is not working atm :)

**Comment by HOSTED-POWER** [comment]
Same with:

```
 '/usr/lib/nagios/plugins/check_es_system.sh' '-H' 'localhost'  '-c' '500' '-t' 'status' -L
EMPTY

```
```
'/usr/lib/nagios/plugins/check_es_system.sh' '-H' 'localhost'  '-c' '500' '-t' 'status'
ES SYSTEM OK - Elasticsearch Cluster "elasticsearch" is green (1 nodes, 1 data nodes, 19 shards, 7051919 docs)|total_nodes=1;;;; data_nodes=1;;;; total_shards=19;;;; relocating_shards=0;;;; initializing_shards=0;;;; unassigned_shards=0;;;; docs=7051919;;;;
```

**Comment by Napsty** [comment]
@HOSTED-POWER thanks! these are indeed important regressions. will take care of it.

**Comment by Napsty** [comment]
@HOSTED-POWER should be fixed now. Please try https://raw.githubusercontent.com/Napsty/check_es_system/pull-41/check_es_system.sh

**Comment by HOSTED-POWER** [comment]
ok perfect, will test, thanks a lot!

**Comment by HOSTED-POWER** [comment]
So far so good as far as I can tell! :)

**Pull request merged**
