### PR TITLE
Added support to jq parser instead of jshon

### LINKED ISSUE #25: check_es_system is not compatible with CentOS/RHEL-based systems
CentOS/RHEL software repositories doesn't have the JSON parser used in check_es_system.sh(jshon)

### PR DESCRIPTION
**Pull request by juanmancebo**
jshon is not compatible with many systems and it isn't available in highly used repos like CentOS/RHEL-based repos.
Closes #25

### CODE REVIEW

**Comment by Napsty** [comment]
before you do too much work, I prefer to merge #19 which allows multiple json parsers

**Comment by juanmancebo** [comment]
> before you do too much work, I prefer to merge #19 which allows multiple json parsers

I think there are no advantages in maintaining multiple JSON parsers in this case, because jq is available in all operating systems (linux,mac,windows,solaris...).
If you want to maintain both parsers (for any reason), it will be more difficult to maintain the script.
As you can see the usage of jq is really simple. I'm using this fork with jq in Ubuntu and CentOS without any problem.

**Comment by Napsty** [comment]
I appreciate your concern - but I kind of like maintaining these monitoring plugins ;-)
My primary goal is to ensure backward compatibility. Someone using the plugin already should just replace the plugin with the new version and everything continues without having to adjust configs. 
By removing jshon completely, this would break backward compatibility.

I have now merged #19 to master and fixed the jshon parsing order. I tested the new master version  successfully with both jq and jshon on the following types:

- status
- disk
- mem
- readonly
- tps
- master
- jthreads

Please give it a shot.

**Comment by juanmancebo** [comment]
Hi,

you're right with the lack of backward compatibility in this PR. I didn't keep it in mind.

Thanks.

**Pull request closed without merging**
